export default interface IUsuario{
    id:number;
    name:string;
    email:string;
    rol:string;
    permisos:{
        lectura:boolean;
        escritura:boolean;
        actualizacion:boolean;
        eliminacion:boolean;
        accesoRemoto:boolean;
        puedeAsignarPermisos:boolean;
    }
    address:{
        street:string;
        suite:string;
        city:string;
        zipcode:string;
        geo:{
            lat:string;
            lng:string
        }
    }
    phone:string;
    website:string;
    company:{
        name:string;
        catchPhrase:string;
        bs:string;
    }
}